name = "blastr"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

# replace with your info
routes = [
    { pattern = "nostr.mutinywallet.com/", zone_id = "2b9268714ce8d1c4431e8046d4ba55d3" },
    { pattern = "nostr.mutinywallet.com/event", zone_id = "2b9268714ce8d1c4431e8046d4ba55d3" }
]

kv_namespaces = [
  { binding = "PUBLISHED_NOTES", id = "afa24a392a5a41f6b1655507dfd9b97a", preview_id = "0b334aece8d74c3ab90e3e99db569ce8" }
]

[vars]
WORKERS_RS_VERSION = "0.0.11"

[[queues.producers]]
 queue = "nostr-events-pub-1"
 binding = "nostr-events-pub-1"

[[queues.producers]]
 queue = "nostr-events-pub-2"
 binding = "nostr-events-pub-2"

[[queues.producers]]
 queue = "nostr-events-pub-3"
 binding = "nostr-events-pub-3"

[[queues.producers]]
 queue = "nostr-events-pub-4"
 binding = "nostr-events-pub-4"

[[queues.producers]]
 queue = "nostr-events-pub-5"
 binding = "nostr-events-pub-5"

[[queues.producers]]
 queue = "nostr-events-pub-6-a"
 binding = "nostr-events-pub-6-a"

[[queues.producers]]
 queue = "nostr-events-pub-7"
 binding = "nostr-events-pub-7"

[[queues.producers]]
 queue = "nostr-events-pub-8"
 binding = "nostr-events-pub-8"

[[queues.producers]]
 queue = "nostr-events-pub-9"
 binding = "nostr-events-pub-9"

[[queues.producers]]
 queue = "nostr-events-pub-10"
 binding = "nostr-events-pub-10"

# consumers
[[queues.consumers]]
 queue = "nostr-events-pub-1"
 max_batch_size = 15
 max_batch_timeout = 5 # this is the best one, run quicker

[[queues.consumers]]
 queue = "nostr-events-pub-2"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-3"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-4"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-5"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-6-a"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-7"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-8"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-9"
 max_batch_size = 20
 max_batch_timeout = 15

[[queues.consumers]]
 queue = "nostr-events-pub-10"
 max_batch_size = 20
 max_batch_timeout = 15

[build]
command = "cargo install --git https://github.com/CathalMullan/workers-rs worker-build && worker-build --release"
#command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
