name = "blastr"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

# replace with your info
routes = [
    { pattern = "nostr.mutinywallet.com/", zone_id = "2b9268714ce8d1c4431e8046d4ba55d3" },
    { pattern = "nostr.mutinywallet.com/event", zone_id = "2b9268714ce8d1c4431e8046d4ba55d3" }
]

[vars]
WORKERS_RS_VERSION = "0.0.11"

[[queues.producers]]
 queue = "nostr-events-pub"
 binding = "nostr-events-pub"

[[queues.producers]]
 queue = "nostr-events-pub-2"
 binding = "nostr-events-pub-2"

[[queues.producers]]
 queue = "nostr-events-pub-3"
 binding = "nostr-events-pub-3"

[[queues.producers]]
 queue = "nostr-events-pub-4"
 binding = "nostr-events-pub-4"

[[queues.producers]]
 queue = "nostr-events-pub-5"
 binding = "nostr-events-pub-5"

[[queues.producers]]
 queue = "nostr-events-pub-6"
 binding = "nostr-events-pub-6"

[[queues.consumers]]
 queue = "nostr-events-pub"
 max_batch_size = 10
 max_batch_timeout = 30

[[queues.consumers]]
 queue = "nostr-events-pub-2"
 max_batch_size = 10
 max_batch_timeout = 30

[[queues.consumers]]
 queue = "nostr-events-pub-3"
 max_batch_size = 10
 max_batch_timeout = 30

[[queues.consumers]]
 queue = "nostr-events-pub-4"
 max_batch_size = 10
 max_batch_timeout = 30

[[queues.consumers]]
 queue = "nostr-events-pub-5"
 max_batch_size = 10
 max_batch_timeout = 30

[[queues.consumers]]
 queue = "nostr-events-pub-6"
 max_batch_size = 10
 max_batch_timeout = 30

[build]
command = "cargo install --git https://github.com/CathalMullan/workers-rs worker-build && worker-build --release"
#command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
